import { LegalDisclaimer } from '@/components/ui/legal-disclaimer'

export default function DisclaimerPage() {
  return (
    <div className="max-w-4xl mx-auto py-8">
      <h1 className="text-3xl font-bold text-gray-900 mb-8">Legal Disclaimer</h1>

      <LegalDisclaimer />

      <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-8 space-y-6 text-gray-700 mt-6">
        <section>
          <h2 className="text-xl font-semibold text-gray-900 mb-3">Understanding Document Automation</h2>
          <p>
            Legal Doc Automation is a technology platform that uses artificial intelligence to generate legal document
            templates based on information you provide. While we strive for accuracy and quality, this service has
            important limitations you should understand:
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900 mb-3">What This Service Is</h2>
          <ul className="list-disc list-inside space-y-2 ml-4">
            <li>A document template generator</li>
            <li>A time-saving tool for creating draft legal documents</li>
            <li>A starting point for legal paperwork</li>
            <li>An automation platform that uses AI technology</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900 mb-3">What This Service Is NOT</h2>
          <ul className="list-disc list-inside space-y-2 ml-4">
            <li>A law firm or legal practice</li>
            <li>A substitute for legal advice from a licensed attorney</li>
            <li>A replacement for professional legal representation</li>
            <li>A guarantee of any legal outcome</li>
            <li>A court-approved service (documents still require court acceptance)</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900 mb-3">Why You Should Consult an Attorney</h2>
          <p className="mb-2">
            Every legal situation is unique and complex. An attorney can provide services that this platform cannot:
          </p>
          <ul className="list-disc list-inside space-y-2 ml-4">
            <li><strong>Legal Strategy:</strong> Advise on the best approach for your specific case</li>
            <li><strong>Personalized Analysis:</strong> Evaluate your situation considering all relevant factors</li>
            <li><strong>Negotiation:</strong> Represent you in discussions with opposing parties</li>
            <li><strong>Court Representation:</strong> Advocate for you in court proceedings</li>
            <li><strong>Document Review:</strong> Ensure documents are properly tailored to your case</li>
            <li><strong>Legal Compliance:</strong> Ensure all requirements and deadlines are met</li>
            <li><strong>Risk Assessment:</strong> Identify potential issues before they become problems</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900 mb-3">Limitations of AI-Generated Documents</h2>
          <p className="mb-2">While our AI is sophisticated, it has limitations:</p>
          <ul className="list-disc list-inside space-y-2 ml-4">
            <li>AI cannot understand nuances of your specific situation</li>
            <li>AI cannot provide strategic legal advice</li>
            <li>AI may not be aware of recent changes in law or court procedures</li>
            <li>AI cannot predict how a judge will rule in your case</li>
            <li>AI generates documents based on patterns, not legal expertise</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900 mb-3">Your Responsibilities</h2>
          <p className="mb-2">When using this service, you are responsible for:</p>
          <ul className="list-disc list-inside space-y-2 ml-4">
            <li>Providing accurate and complete information</li>
            <li>Reviewing all generated documents thoroughly</li>
            <li>Having documents reviewed by a licensed attorney</li>
            <li>Ensuring compliance with all court rules and requirements</li>
            <li>Verifying that documents meet your specific needs</li>
            <li>Understanding the legal implications of the documents you file</li>
            <li>Making your own informed decisions about your legal matters</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900 mb-3">Specific Risks and Disclaimers</h2>

          <h3 className="font-semibold text-gray-900 mt-4 mb-2">Document Acceptance</h3>
          <p>
            We cannot guarantee that courts will accept documents generated by this service. Court requirements vary
            by county and can change without notice.
          </p>

          <h3 className="font-semibold text-gray-900 mt-4 mb-2">Legal Outcomes</h3>
          <p>
            We make no representations about the likelihood of success in your legal matter. Legal outcomes depend on
            many factors beyond the documents themselves.
          </p>

          <h3 className="font-semibold text-gray-900 mt-4 mb-2">Deadlines and Timing</h3>
          <p>
            You are responsible for meeting all legal deadlines. Failure to file documents on time can result in serious
            consequences, including dismissal of your case or default judgment.
          </p>

          <h3 className="font-semibold text-gray-900 mt-4 mb-2">Accuracy of Information</h3>
          <p>
            The quality of generated documents depends on the accuracy of information you provide. Incomplete or incorrect
            information will result in inadequate documents.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900 mb-3">Finding Legal Help</h2>
          <p className="mb-2">If you need legal assistance, consider these resources:</p>
          <ul className="list-disc list-inside space-y-2 ml-4">
            <li><strong>California State Bar:</strong> Find licensed attorneys at{' '}
              <a href="https://www.calbar.ca.gov" target="_blank" rel="noopener noreferrer" className="text-blue-600 hover:underline">
                calbar.ca.gov
              </a>
            </li>
            <li><strong>Legal Aid:</strong> Free or low-cost legal services for qualifying individuals</li>
            <li><strong>Local Bar Association:</strong> Many counties offer lawyer referral services</li>
            <li><strong>Court Self-Help Centers:</strong> Free assistance available at many courthouses</li>
          </ul>
        </section>

        <section className="bg-red-50 border border-red-200 rounded-lg p-6">
          <h2 className="text-xl font-semibold text-red-900 mb-3">⚠️ When You MUST Consult an Attorney</h2>
          <p className="mb-2 text-red-900">You should seek professional legal advice if:</p>
          <ul className="list-disc list-inside space-y-2 ml-4 text-red-900">
            <li>Your case involves complex issues or significant assets</li>
            <li>There is domestic violence or safety concerns</li>
            <li>Child custody is contested</li>
            <li>Your spouse has an attorney</li>
            <li>You face criminal charges</li>
            <li>You are unsure about your legal rights</li>
            <li>Court proceedings are already underway</li>
            <li>You need representation in court</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900 mb-3">Agreement to Terms</h2>
          <p>
            By using Legal Doc Automation, you acknowledge that you have read and understood this disclaimer and agree
            to its terms. You understand that this service does not provide legal advice and that you should consult
            with a licensed attorney for legal advice specific to your situation.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900 mb-3">Questions or Concerns</h2>
          <p>
            If you have questions about this disclaimer or how to use the service appropriately, please contact us at{' '}
            <a href="mailto:support@legaldocautomation.com" className="text-blue-600 hover:underline">
              support@legaldocautomation.com
            </a>
          </p>
        </section>

        <div className="border-t border-gray-200 pt-6 mt-8">
          <p className="text-sm text-gray-500">
            <strong>Last Updated:</strong> January 2025
          </p>
        </div>
      </div>
    </div>
  )
}
