'use client'

import { AlertTriangle } from 'lucide-react'

export function LegalDisclaimer({ compact = false }: { compact?: boolean }) {
  if (compact) {
    return (
      <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-3 mb-4">
        <div className="flex items-start gap-2">
          <AlertTriangle className="w-5 h-5 text-yellow-600 flex-shrink-0 mt-0.5" />
          <div className="text-sm text-yellow-800">
            <strong>Legal Disclaimer:</strong> This service provides document templates and is not a substitute for legal advice.
            We are not a law firm and do not provide legal representation. For legal advice, consult a licensed attorney.
          </div>
        </div>
      </div>
    )
  }

  return (
    <div className="bg-yellow-50 border-2 border-yellow-300 rounded-lg p-6 mb-6">
      <div className="flex items-start gap-3 mb-4">
        <AlertTriangle className="w-6 h-6 text-yellow-600 flex-shrink-0 mt-1" />
        <h3 className="text-lg font-semibold text-yellow-900">Important Legal Disclaimer</h3>
      </div>

      <div className="space-y-3 text-sm text-yellow-900">
        <p>
          <strong>This is NOT Legal Advice:</strong> The documents generated by this service are templates based on your input.
          They are not a substitute for legal advice from a licensed attorney. Every legal situation is unique, and only a qualified
          attorney can provide advice specific to your circumstances.
        </p>

        <p>
          <strong>We Are Not a Law Firm:</strong> This service does not provide legal representation, and no attorney-client
          relationship is created by using this platform. We are a document automation service only.
        </p>

        <p>
          <strong>Review by Attorney Recommended:</strong> We strongly recommend that you have any documents reviewed by a
          licensed California family law attorney before filing with the court or relying on them for legal purposes.
        </p>

        <p>
          <strong>No Guarantees:</strong> While we strive for accuracy, we cannot guarantee that the generated documents will
          meet all legal requirements for your specific situation or that courts will accept them. You are responsible for
          verifying all information and ensuring compliance with applicable laws.
        </p>

        <p>
          <strong>By using this service, you acknowledge that:</strong>
        </p>
        <ul className="list-disc list-inside space-y-1 ml-4">
          <li>You understand this is not legal advice</li>
          <li>You will not rely solely on these documents without professional review</li>
          <li>You are responsible for the accuracy of information you provide</li>
          <li>You will consult with an attorney for legal advice specific to your case</li>
        </ul>
      </div>
    </div>
  )
}

export function DisclaimerBanner() {
  return (
    <div className="bg-amber-100 border-b border-amber-300 py-2 px-4">
      <div className="max-w-7xl mx-auto flex items-center justify-center gap-2 text-sm text-amber-900">
        <AlertTriangle className="w-4 h-4 flex-shrink-0" />
        <p>
          <strong>Not Legal Advice:</strong> This service generates document templates only.
          Consult a licensed attorney for legal advice.
          <a href="/legal/disclaimer" className="underline ml-1 hover:text-amber-700">
            Learn more
          </a>
        </p>
      </div>
    </div>
  )
}
